# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SessionProtect < Formula
  desc "Protect, explore, and command your AI coding-agent sessions"
  homepage "https://github.com/rexovas/session-protect"
  version "1.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rexovas/session-protect/releases/download/v1.0.1/session-protect_1.0.1_darwin_amd64.tar.gz"
      sha256 "9e592d17f5ae67149c96e9ee6294a622929ac85ef9b831e8ec1125a4b5c38b48"

      define_method(:install) do
        bin.install "session-protect"
        bin.install_symlink "session-protect" => "sp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rexovas/session-protect/releases/download/v1.0.1/session-protect_1.0.1_darwin_arm64.tar.gz"
      sha256 "a3dd6c5d0cf152c70c4315d9aaced1b81116fe1f44a1da774eeb1749966180e2"

      define_method(:install) do
        bin.install "session-protect"
        bin.install_symlink "session-protect" => "sp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rexovas/session-protect/releases/download/v1.0.1/session-protect_1.0.1_linux_amd64.tar.gz"
      sha256 "f5194181d33bbc011df00c119c4f4f4c29c8c7cf77323982045b9e863cda7071"
      define_method(:install) do
        bin.install "session-protect"
        bin.install_symlink "session-protect" => "sp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rexovas/session-protect/releases/download/v1.0.1/session-protect_1.0.1_linux_arm64.tar.gz"
      sha256 "a2296187b2133051458d577d8e9d6522c032ac1ba6296b4177d1bc2c67657fcf"
      define_method(:install) do
        bin.install "session-protect"
        bin.install_symlink "session-protect" => "sp"
      end
    end
  end

  test do
    system "#{bin}/session-protect", "version"
  end
end
